### ISSUE TITLE
Add an alt manager

### ISSUE THREAD

**Issue by l1ving** [kami-blue/client#12]
- [x] zeroeightysix/KAMI#4 (#673)

- [x] zeroeightysix/KAMI#106 [video](https://www.youtube.com/watch?v=72gJgxpJrgE) (see #584)

- [x] zeroeightysix/KAMI#103

- [x] zeroeightysix/KAMI#94

- [x] zeroeightysix/KAMI#95

- [ ] zeroeightysix/KAMI#96

- [x] zeroeightysix/KAMI#97

- [x] zeroeightysix/KAMI#92 (by pr  #113)

- [x] zeroeightysix/KAMI#87 (#354)

- [x] zeroeightysix/KAMI#81 (#790)

- [x] zeroeightysix/KAMI#80 (#289 / #447)

- [x] zeroeightysix/KAMI#75 (#707)

- [x] zeroeightysix/KAMI#72 (#25)

- [x] zeroeightysix/KAMI#129 (#671)

- [x] zeroeightysix/KAMI#69 (#503)

- [x] zeroeightysix/KAMI#56 

- [x] zeroeightysix/KAMI#128 

- [x] zeroeightysix/KAMI#120 (won't fix)

- [x] zeroeightysix/KAMI#45 (#173)

- [x] zeroeightysix/KAMI#20

**Comment by l1ving** [comment]
Closing as last issue is listed in #1648
